# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres
  password: postgres

development:
  <<: *default
  database: games_wishlist_app_development

test:
  <<: *default
  database: games_wishlist_app_test

production:
  primary: &primary_production
    <<: *default
    database: games_wishlist_app_production
    username: games_wishlist_app
    password: <%= ENV["GAMES_WISHLIST_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: games_wishlist_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: games_wishlist_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: games_wishlist_app_production_cable
    migrations_paths: db/cable_migrate
